/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppErrorDevSection: typeof import('./src/components/AppError/AppErrorDevSection.vue')['default']
    AppErrorPage: typeof import('./src/components/AppError/AppErrorPage.vue')['default']
    AppErrorProdSection: typeof import('./src/components/AppError/AppErrorProdSection.vue')['default']
    AuthLayout: typeof import('./src/components/Layout/main/AuthLayout.vue')['default']
    ErrorAlert: typeof import('./src/components/Alerts/ErrorAlert.vue')['default']
    Navigation: typeof import('./src/components/Layout/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavbar: typeof import('./src/components/Layout/TopNavbar.vue')['default']
  }
}
